/**
 * IMAGE CONFIGURATION
 * 
 * This file controls which images appear in each portfolio section.
 * Generated by Admin Panel on 1/18/2026, 8:36:00 PM
 */

const portfolioConfig = {
    track: {
        title: "TRACK &<br>FIELD",
        description: "Track & Field Photography",
        images: [
            "PB1(Track) (11 of 262).jpg",
            "PB1(Track) (33 of 262).jpg",
            "PB1(Track) (36 of 262).jpg",
            "PB1(Track) (67 of 262).jpg",
            "PB1(Track) (76 of 262).jpg",
            "PB1(Track) (79 of 262).jpg",
            "PB1(Track) (87 of 262).jpg",
            "PB1(Track) (90 of 262).jpg",
            "PB1(Track) (116 of 262).jpg",
        ]
    },
    soccer: {
        title: "SOCCER",
        description: "Soccer Photography",
        images: [

        ]
    },
    football: {
        title: "FOOTBALL",
        description: "Football Photography",
        images: [

        ]
    },
    basketball: {
        title: "BASKETBALL",
        description: "Basketball Photography",
        images: [

        ]
    },
    bestOf: {
        title: "BEST<br>OF",
        description: "Curated Selection",
        images: [

        ]
    }
};

// Placeholder images for empty galleries
const placeholderImages = [
    "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
    "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    "https://images.unsplash.com/photo-1566577134770-3d85bb3a9cc4?w=800&q=80",
    "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
];