/**
 * IMAGE CONFIGURATION
 * 
 * This file controls which images appear in each portfolio section.
 * Generated by Admin Panel on 1/18/2026, 10:04:20 PM
 */

const portfolioConfig = {
    track: {
        title: "TRACK &<br>FIELD",
        description: "Track & Field Photography",
        images: [
            "PB1(Track) (36 of 262).jpg",
            "PB1(Track) (11 of 262).jpg",
            "PB1(Track) (33 of 262).jpg",
            "PB1(Track) (67 of 262).jpg",
            "PB1(Track) (76 of 262).jpg",
            "PB1(Track) (79 of 262).jpg",
            "PB1(Track) (87 of 262).jpg",
            "PB1(Track) (90 of 262).jpg",
            "PB1(Track) (116 of 262).jpg",
        ]
    },
    soccer: {
        title: "SOCCER",
        description: "Soccer Photography",
        images: [
            "expo1mp (20 of 430).jpg",
            "expo1mp (192 of 430).jpg",
            "expo1mp (28 of 430).jpg",
            "expo1mp (29 of 430).jpg",
            "expo1mp (38 of 430).jpg",
            "expo1mp (49 of 430).jpg",
            "expo1mp (163 of 430).jpg",
            "expo1mp (76 of 430).jpg",
            "expo1mp (164 of 430).jpg",
            "expo1mp (172 of 430).jpg",
            "expo1mp (248 of 430).jpg",
            "expo1mp (278 of 430).jpg",
            "expo1mp (288 of 430).jpg",
            "expo1mp (292 of 430).jpg",
            "expo1mp (298 of 430).jpg",
            "expo1mp (311 of 430).jpg",
            "expo1mp (313 of 430).jpg",
            "expo1mp (353 of 430).jpg",
            "expo1mp (369 of 430).jpg",
            "expo1mp (380 of 430).jpg",
            "expo1mp (413 of 430).jpg",
            "expo2mp (34 of 164).jpg",
            "expo2mp (46 of 164).jpg",
            "expo2mp (58 of 164).jpg",
            "expo2mp (123 of 164).jpg",
            "expo2mp (133 of 164).jpg",
            "expo2mp (139 of 164).jpg",
            "expo2mp (159 of 164).jpg",
            "expo2mp (162 of 164).jpg",
        ]
    },
    football: {
        title: "FOOTBALL",
        description: "Football Photography",
        images: [

        ]
    },
    basketball: {
        title: "BASKETBALL",
        description: "Basketball Photography",
        images: [

        ]
    },
    bestOf: {
        title: "BEST<br>OF",
        description: "Curated Selection",
        images: [

        ]
    }
};

// Placeholder images for empty galleries
const placeholderImages = [
    "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
    "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    "https://images.unsplash.com/photo-1566577134770-3d85bb3a9cc4?w=800&q=80",
    "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
];