/**
 * IMAGE CONFIGURATION
 * 
 * This file controls which images appear in each portfolio section.
 * Generated by Admin Panel on 1/20/2026, 11:26:09 AM
 */

const portfolioConfig = {
    track: {
        title: "TRACK &<br>FIELD",
        description: "Track & Field Photography",
        homePagePhoto: "PB1(Track) (216 of 262).jpg", // Set to filename to override, null uses first image
        images: [
            "PB1(Track) (216 of 262).jpg",
        ]
    },
    soccer: {
        title: "SOCCER",
        description: "Soccer Photography",
        homePagePhoto: null, // Set to filename to override, null uses first image
        images: [

        ]
    },
    football: {
        title: "FOOTBALL",
        description: "Football Photography",
        homePagePhoto: "Copy of HOMEGAME1(expo2) (131 of 142).jpg", // Set to filename to override, null uses first image
        images: [
            "Copy of HOMEGAME1(expo2) (131 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (140 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (6 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (23 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (78 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (134 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (133 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (129 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (114 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (112 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (105 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (102 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (93 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (76 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (73 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (58 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (53 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (51 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (28 of 142).jpg",
            "Copy of HOMEGAME1(expo2) (25 of 142).jpg",
            "Copy of HOMEGAME1 (343 of 343).jpg",
            "Copy of HOMEGAME1 (322 of 343).jpg",
            "Copy of HOMEGAME1 (300 of 343).jpg",
            "Copy of HOMEGAME1 (291 of 343).jpg",
            "Copy of HOMEGAME1 (285 of 343).jpg",
            "Copy of HOMEGAME1 (287 of 343).jpg",
            "Copy of HOMEGAME1 (286 of 343).jpg",
            "Copy of HOMEGAME1 (281 of 343).jpg",
            "Copy of HOMEGAME1 (276 of 343).jpg",
            "Copy of HOMEGAME1 (257 of 343).jpg",
            "Copy of HOMEGAME1 (253 of 343).jpg",
            "Copy of HOMEGAME1 (251 of 343).jpg",
            "Copy of HOMEGAME1 (246 of 343).jpg",
            "Copy of HOMEGAME1 (245 of 343).jpg",
            "Copy of HOMEGAME1 (241 of 343).jpg",
            "Copy of HOMEGAME1 (174 of 343).jpg",
            "Copy of HOMEGAME1 (156 of 343).jpg",
            "Copy of HOMEGAME1 (155 of 343).jpg",
            "Copy of HOMEGAME1 (135 of 343).jpg",
            "Copy of HOMEGAME1 (134 of 343).jpg",
            "Copy of HOMEGAME1 (130 of 343).jpg",
            "Copy of HOMEGAME1 (129 of 343).jpg",
            "Copy of HOMEGAME1 (118 of 343).jpg",
            "Copy of HOMEGAME1 (111 of 343).jpg",
            "Copy of HOMEGAME1 (110 of 343).jpg",
            "Copy of HOMEGAME1 (109 of 343).jpg",
            "Copy of HOMEGAME1 (192 of 343).jpg",
            "Copy of HOMEGAME1 (104 of 343).jpg",
            "Copy of HOMEGAME1 (79 of 343).jpg",
            "Copy of HOMEGAME1 (78 of 343).jpg",
            "Copy of HOMEGAME1 (75 of 343).jpg",
            "Copy of HOMEGAME1 (72 of 343).jpg",
            "Copy of HOMEGAME1 (62 of 343).jpg",
            "Copy of HOMEGAME1 (13 of 343).jpg",
            "Copy of HOMEGAME1 (5 of 343).jpg",
            "Copy of HOMEGAME1 (3 of 343).jpg",
        ]
    },
    basketball: {
        title: "BASKETBALL",
        description: "Basketball Photography",
        homePagePhoto: null, // Set to filename to override, null uses first image
        images: [

        ]
    },
    bestOf: {
        title: "BEST<br>OF",
        description: "Curated Selection",
        homePagePhoto: null, // Set to filename to override, null uses first image
        images: [

        ]
    }
};
};

// Placeholder images for empty galleries
const placeholderImages = [
    "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
    "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    "https://images.unsplash.com/photo-1566577134770-3d85bb3a9cc4?w=800&q=80",
    "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
];